### ISSUE TITLE
Feature request: unlimited timer

### ISSUE THREAD

**Issue by xenotropic** [AmruthPillai/All-The-Words-That-I-Know#1]
It would be nice to have a version where you just do it not for speed, but just something to do for more time, like a crossword puzzle. So perhaps create in addition to "easy" "medium" and "hard", a level that is "lazy game" or whatever you want to call it, where there is no timer. Thanks for creating the original, and considering this request!

**Comment by AmruthPillai** [comment]
This has been implemented, and deployed to https://pillai.xyz/word-game :)
Hope you enjoy playing!
