### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by GrpeApple** [AmruthPillai/All-The-Words-That-I-Know#3]
https://pillai.xyz/word-game
> Site Not Found
> Why am I seeing this?
> 
> There are a few potential reasons:
> 
>     You haven't deployed an app yet.
>     You may have deployed an empty directory.
>    This is a custom domain, but we haven't finished setting it up yet.
> 
> How can I deploy my first app?
> 
> Refer to our hosting documentation to get started.

**Comment by AmruthPillai** [comment]
Oh, I actually had to take this project down because I was crossing my free project limit on Firebase. Let me see if I can bring it back up some time.

**Comment by AmruthPillai** [comment]
I've re-deployed the game, and is available on the same URL: **https://pillai.xyz/word-game** :)

**Comment by ghost** [comment]
Thank you
